# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JannatifarTinaFinalProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
   pod 'GooglePlaces', '7.2.0'
  

  # Pods for JannatifarTinaFinalProject

  target 'JannatifarTinaFinalProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'JannatifarTinaFinalProjectUITests' do
    # Pods for testing
  end

end
